services:

  backend:
    build: .
    ports:
      - "8000:8000"
    restart: always
    environment:
      PORT: 8000
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: mongodb://mongodb:27017/portfolioDB
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - portfolio

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - portfolio

networks:
  portfolio:
      driver: bridge

volumes:
  mongo-data: